FROM python:3.10-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

COPY . .

RUN chmod +x wait-for-it.sh
RUN chmod +x entrypoint.tests.sh

CMD ["sh", "entrypoint.tests.sh"]