version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_db


volumes:
  postgres_data: