version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
      - db
      - rabbitmq
      - celery_worker

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_db
    ports:
      - "5555:5432"

  redis:
    image: redis:7-alpine

  rabbitmq:
    image: rabbitmq:3.12-alpine

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    restart: always
    volumes:
      - ./src/menu/admin:/app/src/menu/admin
    env_file:
      - .env
    depends_on:
      - rabbitmq
      - redis

volumes:
  postgres_data:
