version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./:/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env_db

  redis:
    image: redis:7-alpine


volumes:
  postgres_data:
